baseURL: https://sherrieg.com
languageCode: en-us
defaultContentLanguage: en
title: Sherrie Gossett's blog
theme: feather
enableRobotsTXT: true
timeout: 45000
enableGitInfo: true
buildDrafts: true

build:
  writeStats: true

outputs:
  home:
    - HTML
    - RSS
  section:
    - HTML
    - RSS
    - JSON

permalinks:
  blog: /:filename/

imaging:
  quality: 100

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /blog/
      weight: 2

  footer_nav:
    - name: Built With
      url: /built-with/
      weight: 1
    - name: License
      url: /license/
      weight: 2
    - name: See an Issue?
      url: https://github.com/SherG/sherrieg/issues
      weight: 3

params:
  show_search: true
  show_debug_table: false
  goat_counter_code: sherrieg
  date_format: Jan 2, 2006

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: pygments
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
